Import needed libraries

In [1]:
import pandas as pd
import numpy as np

### Perceptron Classifier

This class implements properties of a perceptron classifier. It first initializes needed values like learning rate and input data points and weights matrix which represents coefficients of equation of the plane.

In train method, network iterates on input data and adjust weights to separate points with labels 1 and -1. The training process is as below:

Prediction:
$$label = 1: w\times x+bias\gt 0$$
$$label = 0: w\times x+bias\le 0$$

Error Calculation:
$$error = TrueLabel - PredLabel$$

weight update:
$$w = w + \lambda\times error\times x$$
$$bias = bias + \lambda\times error$$

In [2]:
class Perceptron:

    def __init__(self, data, lr=0.01, max_epochs=100):
        self.data = data
        self.learning_rate = lr
        self.max_epochs = max_epochs
        self.weights = np.array([-1, -1, -1], dtype=float)
        self.bias = 0


    def train(self):
        for epoch in range(self.max_epochs):
            total_error = 0
            for point in self.data:

                # calculate the weighted sum: ws = w * x + b
                weighted_sum = np.dot(self.weights, point[:-1]) + self.bias

                # activation function
                output = self.activation_function(weighted_sum)

                # calculate the error
                error = point[-1] - output

                # update weights and bias
                self.weights += self.learning_rate * error * point[:-1]
                self.bias += self.learning_rate * error

                # calculate total false predictions
                total_error += 1 if error>0 else 0
            print(f"Epoch {epoch+1}: Total Error: {total_error}")

            # If no error in all data points, the data is perfectly classified
            if total_error == 0:
                print(f"Training completed after {epoch + 1} epochs")
                break

    def test(self, point):
        weighted_sum = np.dot(self.weights, point) + self.bias
        return self.activation_function(weighted_sum)
    

    def activation_function(self, ws):
        return 1 if ws > 0 else -1
        

    

Read and preprocess the data

In [3]:
address = "dataset/Q1data.csv"

# read the CSV file and convert it to a numpy array
df = pd.read_csv(address)
data = df.to_numpy().astype(float)

$\lambda=0.01$

In [7]:
pc = Perceptron(data, lr=0.01, max_epochs=1000)
pc.train()
print(pc.weights)

Epoch 1: Total Error: 17
Epoch 2: Total Error: 3
Epoch 3: Total Error: 11
Epoch 4: Total Error: 8
Epoch 5: Total Error: 5
Epoch 6: Total Error: 4
Epoch 7: Total Error: 5
Epoch 8: Total Error: 4
Epoch 9: Total Error: 3
Epoch 10: Total Error: 0
Training completed after 10 epochs
[ 35.50837653 -67.43365565   9.65135   ]


$\lambda=0.1$

In [4]:
pc = Perceptron(data, lr=0.1, max_epochs=1000)
pc.train()
print(pc.weights)

Epoch 1: Total Error: 14
Epoch 2: Total Error: 9
Epoch 3: Total Error: 14
Epoch 4: Total Error: 5
Epoch 5: Total Error: 6
Epoch 6: Total Error: 4
Epoch 7: Total Error: 0
Training completed after 7 epochs
[ 323.35805421 -611.71021479   94.48523239]


$\lambda=0.5$

In [5]:
pc = Perceptron(data, lr=0.5, max_epochs=1000)
pc.train()
print(pc.weights)

Epoch 1: Total Error: 15
Epoch 2: Total Error: 16
Epoch 3: Total Error: 2
Epoch 4: Total Error: 8
Epoch 5: Total Error: 6
Epoch 6: Total Error: 5
Epoch 7: Total Error: 3
Epoch 8: Total Error: 4
Epoch 9: Total Error: 2
Epoch 10: Total Error: 2
Epoch 11: Total Error: 4
Epoch 12: Total Error: 2
Epoch 13: Total Error: 2
Epoch 14: Total Error: 0
Training completed after 14 epochs
[ 2186.87605612 -4134.55375094   581.57066097]


$\lambda=2$

In [6]:
pc = Perceptron(data, lr=2, max_epochs=1000)
pc.train()
print(pc.weights)

Epoch 1: Total Error: 15
Epoch 2: Total Error: 16
Epoch 3: Total Error: 2
Epoch 4: Total Error: 8
Epoch 5: Total Error: 6
Epoch 6: Total Error: 5
Epoch 7: Total Error: 3
Epoch 8: Total Error: 4
Epoch 9: Total Error: 2
Epoch 10: Total Error: 2
Epoch 11: Total Error: 2
Epoch 12: Total Error: 5
Epoch 13: Total Error: 4
Epoch 14: Total Error: 5
Epoch 15: Total Error: 3
Epoch 16: Total Error: 1
Epoch 17: Total Error: 3
Epoch 18: Total Error: 4
Epoch 19: Total Error: 3
Epoch 20: Total Error: 0
Training completed after 20 epochs
[  9854.1813211  -18687.45344162   2709.78170996]


$\lambda=10$

In [11]:
pc = Perceptron(data, lr=15, max_epochs=1000)
pc.train()
print(pc.weights)

Epoch 1: Total Error: 15
Epoch 2: Total Error: 16
Epoch 3: Total Error: 2
Epoch 4: Total Error: 8
Epoch 5: Total Error: 6
Epoch 6: Total Error: 5
Epoch 7: Total Error: 3
Epoch 8: Total Error: 4
Epoch 9: Total Error: 2
Epoch 10: Total Error: 2
Epoch 11: Total Error: 2
Epoch 12: Total Error: 5
Epoch 13: Total Error: 4
Epoch 14: Total Error: 5
Epoch 15: Total Error: 3
Epoch 16: Total Error: 1
Epoch 17: Total Error: 3
Epoch 18: Total Error: 4
Epoch 19: Total Error: 3
Epoch 20: Total Error: 0
Training completed after 20 epochs
[  73912.85990821 -140149.40081216   20329.86282472]


After training network with different $\lambda$ values, we can see that when $\lambda$ is too small like 0.01 simulation takes a bit longer. $\lambda=0.1$ has the best result and finishes in 7 epochs. for larger values of $\lambda=0.5, 2, 10$ it gets worse.